PPO_CONFIG:
    algo: PPO
    batch_size: 512
    clip_range: 0.1
    device: cpu
    ent_coef: 0.005
    gae_lambda: 0.95
    gamma: 0.99
    learning_rate: 0.0001
    max_grad_norm: 0.4
    n_epochs: 10
    n_steps: 8192
    normalize_advantage: true
    partition: Krater
    policy: MlpPolicy
    seed: 0
    tensorboard_log: true
    timesteps: 300000000.0
    verbose: 1
    vf_coef: 0.5
---
ENV_CONFIG:
    clip_reward: 10
    env_id: HumanoidEnvCurr
    env_kwargs: {}
    exclude_absolute_height: true
    falling_punishment: 0
    geom_z_gap: 0.001
    healthy_z_range: [-10, 10]
    max_steps: 0
    min_diff_torso_feet: 0.4
    n_envs: 12
    n_points_x: 6
    n_points_y: 5
    norm_obs: true
    norm_reward: true
    render_lidar: true
    seed: 0
    stabilize_lidar: true
    terminate_at_x_border: 60
    use_levels: true
    use_lidar: true
    use_relative_height: false
    x_forward: 4
    x_start: 0
    xml_file: humanoid_curr.xml
    y_width: 1.5
---
CURR_CONFIG:
    buffer_init_fill_ratio: 0.2
    buffer_init_lower_cap: [-0.05, 0, 0, 0, 0]
    buffer_init_upper_cap: [0.45, 0.07, 0.07, 0.1, 0.1]
    buffer_size: 200
    evaluation_episode_steps: 2500
    level_metric: lrn
    mutation_edit_size: [-0.03, 0.03]
    mutation_number: 2
    mutation_usage: false
    replay_decision_distribution: [0.5, 0.5]
    seed: null
    selection_temp: 0.5
    use_curr: true
---
CALLBACK_CONFIG:
    checkpoint_cb_conf:
        name_prefix: ckpt
        save_freq: 3000000
        save_vecnormalize: true
    eval_env_conf:
        deterministic: true
        env_seed: 0
        eval_freq: 500000
        eval_freq_obstacles: 500000
        eval_levels:
        -   name: plain
            params: [0, 0, 0, 0, 0]
            seed: 0
        -   name: slabs
            params: [1, 0.4, 0, 0, 0]
            seed: 42
        -   name: stairs
            params: [1, 0, 0.4, 0, 0]
            seed: 874
        -   name: stumps
            params: [1, 0, 0, 0.4, 0]
            seed: 21
        -   name: gaps
            params: [1, 0, 0, 0, 0.5]
            seed: 21
        -   name: easy
            params: [0.25, 0.2, 0.2, 0.2, 0.2]
            seed: 54090
        -   name: medium
            params: [0.5, 0.4, 0.4, 0.4, 0.4]
            seed: 799
        -   name: hard
            params: [0.75, 0.5, 0.5, 0.5, 0.5]
            seed: 180
        -   name: extrem
            params: [0.9, 0.8, 0.8, 0.8, 0.8]
            seed: 52
        max_steps: 2000
        n_envs: 10
        n_eval_episodes: 10
        render: false
    plot_callback:
        log_level: 2
        window: 100
